# Generated by Django 4.2.15 on 2024-09-21 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_moto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milage', models.PositiveIntegerField(verbose_name='Пробег')),
                ('year', models.SmallIntegerField(verbose_name='Год регистрации')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.car', verbose_name='Машина')),
                ('moto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.moto', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Пробег',
                'verbose_name_plural': 'Пробег',
                'ordering': ('-year',),
            },
        ),
    ]
