# Generated by Django 4.2.15 on 2024-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_car_owner_moto_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год регистрации авто'),
        ),
        migrations.AddField(
            model_name='moto',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год регистрации мото'),
        ),
    ]
