# Generated by Django 4.2.15 on 2024-10-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_car_year_moto_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='year',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='year',
        ),
    ]
